### ISSUE TITLE
Add a "real" copy object option

### ISSUE THREAD

**Issue by StevenCostiou** [pharo-spec/Chest#14]
The current "copy" is actually a copy of the object reference.
It would be interesting to have a "copy object" (perhaps with options, shallow and deep copy?) to duplicate and store objects for backup or future use?

**Comment by adri09070** [comment]
From what I understand, you'd like to have a real copy version of "Store object in a chest" and not "Copy object in a clipboard chest", right?

![image](https://github.com/pharo-spec/Chest/assets/97704417/4c2b8b48-8dac-4229-920e-8ec3918fed02)

**Comment by StevenCostiou** [comment]
yes :)
