### ISSUE TITLE
Enhancement : paste code to get Chest content

### ISSUE THREAD

**Issue by labordep** [pharo-spec/Chest#7]
I think this enhancement will be very cool :) 
The idea is to use stored value in Chest directly in a Playground (or generaly a text input) by pasting chest access code.

1 - I have an object in an inspector. I can place this object into a Chest, easy.
![image](https://user-images.githubusercontent.com/49183340/227717518-3c21a3da-f4b5-471a-bd28-802c3bfb2e9a.png)

2 - I have my object in a Chest.
![image](https://user-images.githubusercontent.com/49183340/227717759-d186f41e-4b02-4a90-a8f3-a1a04f253c0c.png)

3 - Now I want to use it in a playground, so I think it will be good to have a **source code injection** to get my var. The idea is to automatically paste the access code. For example I want to get my var in a playground like that : 
![image](https://user-images.githubusercontent.com/49183340/227717820-d5b91d4e-da35-46a6-8e04-f31e610cd9e9.png)

Do right clic to open a contextual menu with an item like "Past object from chest", here an example with the current menu :

![image](https://user-images.githubusercontent.com/49183340/227717854-8a4fe4b2-e8a5-4c86-a494-fb186226fe0b.png)

This menu can propose all chest and all var to select speadly the good var : `Past object from chest > chest1 > var1 `

And finally the paste can be : 

```smalltalk
myVar := Chest name: #chest1 var: #var1.
```

Were the paste code will be `Chest name: #chest1 var: #var1`.

**Comment by adri09070** [comment]
I think this is a great idea!

**Comment by adri09070** [comment]
This is available in https://github.com/pharo-spec/Chest/releases/tag/v0.5.0
